services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000
      - PORT=3001
      - HOSTNAME=0.0.0.0
    ports:
      - '3001:3001'
    depends_on:
      - api
    networks:
      - my-network

  ppe-detection:
    build:
      context: ./apps/ppe-detection
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - my-network

networks:
  my-network:
    external: true
