export enum UserRole {
  WAREHOUSE_STAFF = 'warehouse staff',
  GROUP_LEADER = 'group leader',
  SECTION_HEAD = 'section head',
  SUPER_ADMIN = 'super admin',
}

export enum QueueStatus {
  MENUNGGU = 'MENUNGGU',
  DISETUJUI = 'DISETUJUI',
  DITOLAK = 'DITOLAK',
  SELESAI = 'SELESAI',
}

export enum ChecklistItemType {
  UMUM = 'UMUM',
  KHUSUS = 'KHUSUS',
}

export enum AuditLogAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  CHECKIN_CREATE = 'CHECKIN_CREATE',
  CHECKIN_APPROVE = 'CHECKIN_APPROVE',
  CHECKIN_REJECT = 'CHECKIN_REJECT',
  CHECKIN_CHECKOUT = 'CHECKIN_CHECKOUT',
  CHECKLIST_CATEGORY_CREATE = 'CHECKLIST_CATEGORY_CREATE',
  CHECKLIST_CATEGORY_UPDATE = 'CHECKLIST_CATEGORY_UPDATE',
  CHECKLIST_CATEGORY_DELETE = 'CHECKLIST_CATEGORY_DELETE',
  CHECKLIST_ITEM_CREATE = 'CHECKLIST_ITEM_CREATE',
  CHECKLIST_ITEM_UPDATE = 'CHECKLIST_ITEM_UPDATE',
  CHECKLIST_ITEM_DELETE = 'CHECKLIST_ITEM_DELETE',
  MATERIAL_CATEGORY_CREATE = 'MATERIAL_CATEGORY_CREATE',
  MATERIAL_CATEGORY_UPDATE = 'MATERIAL_CATEGORY_UPDATE',
  MATERIAL_CATEGORY_DELETE = 'MATERIAL_CATEGORY_DELETE',
  MATERIAL_CATEGORY_BULK_DELETE = 'MATERIAL_CATEGORY_BULK_DELETE',
  MATERIAL_CATEGORY_TOGGLE_STATUS = 'MATERIAL_CATEGORY_TOGGLE_STATUS',
  SYSTEM_CONFIG_UPDATE = 'SYSTEM_CONFIG_UPDATE',
}
