export enum UserRole {
  WAREHOUSE_STAFF = 'warehouse staff',
  GROUP_LEADER = 'group leader',
  SECTION_HEAD = 'section head',
  SUPER_ADMIN = 'super admin',
}

export enum QueueStatus {
  MENUNGGU = 'MENUNGGU',
  DISETUJUI = 'DISETUJUI',
  AKTIF = 'AKTIF',
  TERTAHAN = 'TERTAHAN',
  DITOLAK = 'DITOLAK',
  SELESAI = 'SELESAI',
}

export enum ChecklistItemType {
  UMUM = 'UMUM',
  KHUSUS = 'KHUSUS',
}

export enum AuditLogAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  CHECKIN_CREATE = 'CHECKIN_CREATE',
  CHECKIN_APPROVE = 'CHECKIN_APPROVE',
  CHECKIN_REJECT = 'CHECKIN_REJECT',
  CHECKIN_HOLD = 'CHECKIN_HOLD',
  CHECKIN_RESUME = 'CHECKIN_RESUME',
  CHECKIN_CHECKOUT = 'CHECKIN_CHECKOUT',
  CHECKLIST_CATEGORY_CREATE = 'CHECKLIST_CATEGORY_CREATE',
  CHECKLIST_CATEGORY_UPDATE = 'CHECKLIST_CATEGORY_UPDATE',
  CHECKLIST_CATEGORY_DELETE = 'CHECKLIST_CATEGORY_DELETE',
  CHECKLIST_ITEM_CREATE = 'CHECKLIST_ITEM_CREATE',
  CHECKLIST_ITEM_UPDATE = 'CHECKLIST_ITEM_UPDATE',
  CHECKLIST_ITEM_DELETE = 'CHECKLIST_ITEM_DELETE',
  MATERIAL_CATEGORY_CREATE = 'MATERIAL_CATEGORY_CREATE',
  MATERIAL_CATEGORY_UPDATE = 'MATERIAL_CATEGORY_UPDATE',
  MATERIAL_CATEGORY_DELETE = 'MATERIAL_CATEGORY_DELETE',
  MATERIAL_CATEGORY_BULK_DELETE = 'MATERIAL_CATEGORY_BULK_DELETE',
  MATERIAL_CATEGORY_TOGGLE_STATUS = 'MATERIAL_CATEGORY_TOGGLE_STATUS',
  SYSTEM_CONFIG_UPDATE = 'SYSTEM_CONFIG_UPDATE',
}

export enum ArrivalStatus {
  ON_TIME = 'On-Time',
  LATE = 'Late',
  EARLY = 'Early',
}

export enum DepartureStatus {
  ON_TIME = 'On-Time',
  OVERDUE = 'Overdue',
}

export enum SlotStatus {
  OPEN = 'Open',
  FILLED = 'Filled',
  MISSED = 'Missed',
}

export enum DayOfWeek {
  MONDAY = 1,
  TUESDAY = 2,
  WEDNESDAY = 3,
  THURSDAY = 4,
  FRIDAY = 5,
  SATURDAY = 6,
  SUNDAY = 7,
}

export const DAY_NAMES: Record<number, string> = {
  [DayOfWeek.MONDAY]: 'Senin',
  [DayOfWeek.TUESDAY]: 'Selasa',
  [DayOfWeek.WEDNESDAY]: 'Rabu',
  [DayOfWeek.THURSDAY]: 'Kamis',
  [DayOfWeek.FRIDAY]: 'Jumat',
  [DayOfWeek.SATURDAY]: 'Sabtu',
  [DayOfWeek.SUNDAY]: 'Minggu',
};

export const DAY_OPTIONS = [
  { value: DayOfWeek.MONDAY, label: DAY_NAMES[DayOfWeek.MONDAY] },
  { value: DayOfWeek.TUESDAY, label: DAY_NAMES[DayOfWeek.TUESDAY] },
  { value: DayOfWeek.WEDNESDAY, label: DAY_NAMES[DayOfWeek.WEDNESDAY] },
  { value: DayOfWeek.THURSDAY, label: DAY_NAMES[DayOfWeek.THURSDAY] },
  { value: DayOfWeek.FRIDAY, label: DAY_NAMES[DayOfWeek.FRIDAY] },
  { value: DayOfWeek.SATURDAY, label: DAY_NAMES[DayOfWeek.SATURDAY] },
  { value: DayOfWeek.SUNDAY, label: DAY_NAMES[DayOfWeek.SUNDAY] },
];
