openapi: 3.0.3
info:
  title: Vendor Checkpoint API
  description: |
    API Documentation untuk Sistem Vendor Checkpoint Gudang.
    Mencakup fitur untuk Vendor (Public), Petugas, Leader, dan Admin.
    Tech Stack: NestJS, Prisma, SQL Server.
  version: 1.0.0
  contact:
    name: Bagus Uswanto (Solo Dev)
servers:
  - url: http://localhost:3000/api
    description: Development Server
  - url: https://api.vendorcheckpoint.com
    description: Production Server

tags:
  - name: Auth
    description: Authentication for Staff/Admin
  - name: Public Vendor
    description: Vendor facing endpoints (No Auth)
  - name: Public Display
    description: TV Display endpoints (No Auth)
  - name: Verification
    description: Staff verification process (Sprint 2)
  - name: Operations
    description: Check-out process (Sprint 3)
  - name: Dashboard & Reports
    description: Analytics for Leaders (Sprint 3 & 4)
  - name: Admin Master Data
    description: Configuration management (Sprint 5)

paths:
  # ===========================
  # AUTH (Sprint 2)
  # ===========================
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login Petugas/Admin (FR-07)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        200:
          description: Login successful, returns JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  # ===========================
  # PUBLIC VENDOR (Sprint 1)
  # ===========================
  /vendors/master:
    get:
      tags:
        - Public Vendor
      summary: Get list vendor & categories for Form Identitas (FR-01, FR-02)
      responses:
        200:
          description: List of vendors and categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  vendors:
                    type: array
                    items:
                      $ref: '#/components/schemas/VendorMaster'
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/VendorCategory'

  /checklists/form:
    get:
      tags:
        - Public Vendor
      summary: Get checklist items by vendor category (FR-03)
      parameters:
        - in: query
          name: vendorCategoryId
          schema:
            type: integer
          required: true
          description: ID Kategori Vendor untuk memfilter checklist KHUSUS
      responses:
        200:
          description: Grouped checklist items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistCategoryGroup'

  /checkins:
    post:
      tags:
        - Public Vendor
      summary: Submit Vendor Check-in (FR-04)
      description: Generates queue number and saves responses.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCheckinDto'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckinResult'

  /checkins/status/{queueNumber}:
    get:
      tags:
        - Public Vendor
      summary: Lookup status antrean vendor (FR-05)
      parameters:
        - in: path
          name: queueNumber
          schema:
            type: string
          required: true
          example: '20251212-001'
      responses:
        200:
          description: Current status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueueStatus'

  # ===========================
  # PUBLIC DISPLAY (Sprint 2)
  # ===========================
  /queues/active:
    get:
      tags:
        - Public Display
      summary: Get active queues for TV Display (FR-06)
      description: Auto-refresh data every 10s via Frontend
      responses:
        200:
          description: List of active queues ordered by priority
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueueDisplayItem'

  # ===========================
  # VERIFICATION - STAFF (Sprint 2)
  # ===========================
  /verifications:
    get:
      tags:
        - Verification
      security:
        - bearerAuth: []
      summary: Get list of pending verifications (FR-08)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: search
          schema:
            type: string
            description: Search by driver name or company
      responses:
        200:
          description: Paginated list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationListResponse'

  /verifications/{entryId}:
    get:
      tags:
        - Verification
      security:
        - bearerAuth: []
      summary: Get check-in detail for verification drawer (FR-09)
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Detail with checklist answers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckinDetail'

    post:
      tags:
        - Verification
      security:
        - bearerAuth: []
      summary: Submit Verification Decision (Approve/Reject) (FR-09)
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationDecisionDto'
      responses:
        200:
          description: Verification processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nextStatus:
                    type: string

  # ===========================
  # OPERATIONS - CHECKOUT (Sprint 3)
  # ===========================
  /operations/approved-list:
    get:
      tags:
        - Operations
      security:
        - bearerAuth: []
      summary: Get approved vendors inside warehouse (FR-10)
      responses:
        200:
          description: List for checkout table
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApprovedVendorItem'

  /operations/checkout/{entryId}:
    post:
      tags:
        - Operations
      security:
        - bearerAuth: []
      summary: Process Check-out (FR-10)
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Checked out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  durationMinutes:
                    type: integer
                  checkoutTime:
                    type: string
                    format: date-time

  # ===========================
  # DASHBOARD & REPORTS (Sprint 3 & 4)
  # ===========================
  /dashboard/stats:
    get:
      tags:
        - Dashboard & Reports
      security:
        - bearerAuth: []
      summary: Get daily statistics for dashboard cards (FR-11)
      responses:
        200:
          description: Daily summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardStats'

  /reports/export:
    get:
      tags:
        - Dashboard & Reports
      security:
        - bearerAuth: []
      summary: Download Excel Report (FR-12)
      parameters:
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: categoryId
          schema:
            type: integer
      responses:
        200:
          description: Returns blob/file
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary

  # ===========================
  # ADMIN MASTER DATA (Sprint 5)
  # ===========================
  /admin/vendor-categories:
    get:
      tags:
        - Admin Master Data
      security:
        - bearerAuth: []
      summary: Get all vendor categories (FR-13)
      responses:
        200:
          description: List categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VendorCategory'
    post:
      tags:
        - Admin Master Data
      security:
        - bearerAuth: []
      summary: Create vendor category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VendorCategoryDto'
      responses:
        201:
          description: Created

  /admin/checklists:
    get:
      tags:
        - Admin Master Data
      security:
        - bearerAuth: []
      summary: Get all checklist items for management (FR-14)
      responses:
        200:
          description: Flat list of checklists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistItemAdmin'

    post:
      tags:
        - Admin Master Data
      security:
        - bearerAuth: []
      summary: Create/Update checklist item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChecklistItemDto'
      responses:
        201:
          description: Saved

  /admin/checklists/reorder:
    put:
      tags:
        - Admin Master Data
      security:
        - bearerAuth: []
      summary: Reorder checklist items (FR-14)
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  newOrder:
                    type: integer
      responses:
        200:
          description: Order updated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # --- Auth Schemas ---
    LoginDto:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: 'admin'
        password:
          type: string
          example: 'password123'

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        user:
          type: object
          properties:
            id:
              type: integer
            fullname:
              type: string
            role:
              type: string

    # --- Master Data Schemas ---
    VendorMaster:
      type: object
      properties:
        vendor_id:
          type: integer
        company_name:
          type: string
        vendor_code:
          type: string
        vendor_category_id:
          type: integer

    VendorCategory:
      type: object
      properties:
        vendor_category_id:
          type: integer
        category_name:
          type: string
        category_code:
          type: string

    VendorCategoryDto:
      type: object
      required:
        - category_name
        - category_code
      properties:
        category_name:
          type: string
        category_code:
          type: string

    ChecklistCategoryGroup:
      type: object
      properties:
        category_name:
          type: string
        display_order:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChecklistItemPublic'

    ChecklistItemPublic:
      type: object
      properties:
        checklist_item_id:
          type: integer
        item_text:
          type: string
        item_type:
          type: string
          enum: [UMUM, KHUSUS]
        is_required:
          type: boolean

    ChecklistItemAdmin:
      allOf:
        - $ref: '#/components/schemas/ChecklistItemPublic'
        - type: object
          properties:
            display_order:
              type: integer
            is_active:
              type: boolean

    ChecklistItemDto:
      type: object
      required:
        - item_text
        - checklist_category_id
      properties:
        item_text:
          type: string
        checklist_category_id:
          type: integer
        item_type:
          type: string
          default: 'UMUM'
        vendor_category_id:
          type: integer
          nullable: true

    # --- Transaction Schemas ---
    CreateCheckinDto:
      type: object
      required:
        - vendorId
        - driverName
        - responses
      properties:
        vendorId:
          type: integer
        driverName:
          type: string
        responses:
          type: array
          items:
            type: object
            required:
              - checklistItemId
              - value
            properties:
              checklistItemId:
                type: integer
              value:
                type: boolean
                description: 'true = YA, false = TIDAK'

    CheckinResult:
      type: object
      properties:
        queueNumber:
          type: string
          example: '20251212-001'
        entryId:
          type: integer
        status:
          type: string
        estimatedWaitTime:
          type: integer

    QueueStatus:
      type: object
      properties:
        queueNumber:
          type: string
        status:
          type: string
        statusDisplayText:
          type: string
        updatedAt:
          type: string
          format: date-time

    QueueDisplayItem:
      type: object
      properties:
        queueNumber:
          type: string
        companyName:
          type: string
        driverName:
          type: string
        status:
          type: string
        statusColor:
          type: string
          description: 'Tailwind class e.g. bg-green-500'

    VerificationListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              entryId:
                type: integer
              queueNumber:
                type: string
              driverName:
                type: string
              companyName:
                type: string
              submissionTime:
                type: string
                format: date-time
              nonCompliantCount:
                type: integer
        total:
          type: integer

    CheckinDetail:
      type: object
      properties:
        entry:
          $ref: '#/components/schemas/VerificationListResponse'
        responses:
          type: array
          items:
            type: object
            properties:
              categoryName:
                type: string
              question:
                type: string
              answer:
                type: boolean
              isCompliant:
                type: boolean

    VerificationDecisionDto:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [DISETUJUI, DITOLAK]
        rejectionReason:
          type: string
          description: 'Required if status is DITOLAK'

    ApprovedVendorItem:
      type: object
      properties:
        entryId:
          type: integer
        queueNumber:
          type: string
        companyName:
          type: string
        driverName:
          type: string
        checkinTime:
          type: string
          format: date-time
        duration:
          type: string
          description: 'Elapsed time formatted, e.g. 1h 30m'

    DashboardStats:
      type: object
      properties:
        totalVisitors:
          type: integer
        complianceRate:
          type: number
          format: float
        avgLeadTime:
          type: integer
          description: 'In minutes'
        rejectedCount:
          type: integer
